### PR TITLE
Refactor for GUI upgrade

### PR DESCRIPTION
**Pull request by mrhatman**
Planning to be a bigger update here that I will be tracking. 

I need to make the GUI Usable and somewhat understandable. This will involve along of changes to the code base to make this happen. Currently the GUI communicates with the slicer over a STDIO connection using a message interface. This is slow and over complicates things. The plan is to move all core slicing into gladius core. The idea will be that only the CLI will remain outside the shared interfaces.

The new structure will be something like:

- Gladius Core 
This will contain the main slicer and required functionality. This section will have no side effects allowed in the functions like File io. The idea is that this will be portable and self contained. Testing can also be made to work against this.
- Gladius Shared
This will contain types and helper functions for higher level tools.Loading settings files, logging, etc
- Gladius CLI
The current app that will now be based on Gladius Core
- Gladius GUI
Will be made to use Gladius Core and Shared to allow for shared code.

Tasks:

- [x] Create gladius_core
- [x] Split up existing code into relevant sections 
- [x] Clean up core and interfaces
- [x] Create Preludes for Core and shared
- [x] Create Tests against the main slicer for regression and validation purposes
- [x] Define and document gladius core public facing interfaces
- [x] Audit core for side effects
- [x] Reexport important libraries like geo so there is less need for updates
- [x] Update how logging and state management works
- [x] Update Slicing pass pipeline to be customizable

### CODE REVIEW

**Comment by TimTheBig** [comment]
> Gladius Core
> This will contain the main slicer and required functionality. This section will have no side effects allowed in the functions like File io. The idea is that this will be portable and self contained. Testing can also be made to work against this.

That is a great idea, floating point arithmetic is const stable however the math methods are not. It would be good to use const as much as posible.

**Comment by mrhatman** [comment]
> That is a great idea, floating point arithmetic is const stable however the math methods are not. It would be good to use const as much as possible.

I have moved most of the simple math functions to const.

The issue is that the log functions (warn!(), info!()) are not const nor can they be.

**Comment by mrhatman** [comment]
Also feel free to review the code. I have cleanup to do but its pretty close to being there.

**Comment by TimTheBig** [comment]
> Also feel free to review the code. I have cleanup to do but its pretty close to being there.

Will do

**Comment by TimTheBig** [comment]
It would be a lot easier for me to merge my PR #25 if you merge [Documentation-and-Updates](https://github.com/mrhatman/GladiusSlicer/tree/Documentation-and-Updates) first. Is this based on that branch?

**Comment by mrhatman** [comment]
Yes this is based on that branch. That branch will merge when this one does

**Comment by TimTheBig** [comment]
Looks good to me, though a lot of comments are missing spaces after the '/'s, I know it's a nit pick but you can find them with this regex:
```regex
(?<!:)(\/\/)(\/)?(?!\/|[ \n!])
```

**Pull request merged**
