### PR TITLE
Angled slicing

### PR DESCRIPTION
**Pull request by TimTheBig**
This adds support for slicing along a plane defined be a normal. This can be used to add belt printer support.

Update geo, geo-svg, and serde-xml-rs; reducing duplicate dependencies.
Add more detail to json schema with validator attrs.

- [ ] Calculate normal from angle
- [x] Sort tower with normal
- [x] Fix tower.rs making non circular rings
- [ ] Fix tower.rs making two element rings
- [ ] Make ploter draw lines in 3d

### CODE REVIEW

**Comment by TimTheBig** [comment]
Incomplete rings being too short is my current focus.

**Comment by mrhatman** [comment]
Hello,
I have been working on documenting the main function. I have been pushing some simplifications to the main algorithm as well. I have built a branch that allows for custom vertex Ord. Everything should be correct to function for your needs. 

https://github.com/mrhatman/GladiusSlicer/tree/Documentation-and-Updates

Note the Ord implementation requires that if cmp(a,b) is equal then a nd b are equal. 

Currently a dot normal can be the same for different points. I recommend sorting by a dot normal then if equal x then y, then z. This ensures this constraint.

**Comment by TimTheBig** [comment]
> Hello, I have been working on documenting the main function. I have been pushing some simplifications to the main algorithm as well. I have built a branch that allows for custom vertex Ord. Everything should be correct to function for your needs.
> 
> https://github.com/mrhatman/GladiusSlicer/tree/Documentation-and-Updates

Thank you for letting me know, this will help so much, I will try with this approach.

**Comment by TimTheBig** [comment]
I'm using a new branch #27.

**Pull request closed without merging**
