### PR TITLE
Move to rust 2021 and refacter code.

### PR DESCRIPTION
**Pull request by TimTheBig**
This patch updates dependencies, moves the code base to 2021 edition and improves code readability.

I used my own fork of `geo-offset`, I recommend that you fork it for the GladiusSlicer org.

### CODE REVIEW

**Comment by mrhatman** [comment]
This is likely incompatible with the release candidate, but I like a lot of these changes. 

May I ask what commands you ran for the formatter? 

Later I will merge the candidate in and we can see what kind of issues we see.

**Comment by TimTheBig** [comment]
This patch is based off of the Dev branch; I ran `cargo fmt --all` and manually looked over all changes. All the lints were done by hand.

**Comment by TimTheBig** [comment]
I have fixed all conflicts.

**Comment by mrhatman** [comment]
Looks to good to me.

**Pull request merged**
